### ISSUE TITLE
Get a refresh_token的时候返回：error=access_denied

### ISSUE THREAD

**Issue by icedifferent** [Tai7sy/OneDriveFly#14]
authorization_code?error=access_denied&error_description=AADSTS650051%3a+Using+application+'OneDrive+API'+is+currently+not+supported+for+your+organization+stu.scau.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.scau.edu.cn+before+the+application+OneDrive+API+can+be+provisioned.%0D%0ATrace+ID%3a+8fd3bb22-96d0-4bac-bd1a-9b97d95d6500%0D%0ACorrelation+ID%3a+ab213287-b2f8-45df-8d0b-b21943c714d2%0D%0ATimestamp%3a+2019-07-19+15%3a15%3a04Z

请问一下这种是什么原因导致的？

**Comment by Tai7sy** [comment]
你的账户目前没有管理员，无法使用api
Using+application+'OneDrive+API'+is+currently+not+supported+for+your+organization+stu.scau.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.scau.edu.cn+before+the+application+OneDrive+API+can+be+provisioned
